nav: 
  - begraensa-input.md
  - game-states.md
  - ga-igenom-en-array.md
  - laenkade-listor-och-andra-strukturer.md
  - ta-bort-saker-ur-listan-man-gar-igenom.md
  - 2d-spelbraeden.md
  - timers.md
