nav: 
  - oeversikt-objektorientering.md
  - lathund-foer-klassdesign.md
  - klasser-och-instanser.md
  - struct.md
  - public-private-och-protected.md
  - klassdiagram.md
  - klassmetoder.md
  - kontruktorer.md
  - arv.md
  - komposition.md
  - inkapsling-och-properties.md
  - static.md
  - Polymorfism […]: polymorfism
  - generiska-klasser.md
  - abstract.md
  - interface.md
  - attribut.md
