nav: 
  - README.md
  - lathund-skapa-projekt.md
  - lathund-konsolen.md
  - lathund-wpf.md
  - kompilering-och-publicering.md
  - externa-resurser.md
  - Grundläggande: grundlaeggande
  - Filhantering: filhantering
  - Klasser och objektorientering: klasser-och-objektorientering
  - Annat: annat
  - Mjukvara: mjukvara
  - Tekniker: tekniker
  - contributing.md
